// Code generated by "stringer -type=PacketType,CipherCryptoAlg,CipherBlockMethod -output stringer.go"; DO NOT EDIT.

package ovpn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[P_CONTROL_HARD_RESET_CLIENT_V1-1]
	_ = x[P_CONTROL_HARD_RESET_SERVER_V1-2]
	_ = x[P_CONTROL_SOFT_RESET_V1-3]
	_ = x[P_CONTROL_V1-4]
	_ = x[P_ACK_V1-5]
	_ = x[P_DATA_V1-6]
	_ = x[P_DATA_V2-9]
	_ = x[P_CONTROL_HARD_RESET_CLIENT_V2-7]
	_ = x[P_CONTROL_HARD_RESET_SERVER_V2-8]
}

const _PacketType_name = "P_CONTROL_HARD_RESET_CLIENT_V1P_CONTROL_HARD_RESET_SERVER_V1P_CONTROL_SOFT_RESET_V1P_CONTROL_V1P_ACK_V1P_DATA_V1P_CONTROL_HARD_RESET_CLIENT_V2P_CONTROL_HARD_RESET_SERVER_V2P_DATA_V2"

var _PacketType_index = [...]uint8{0, 30, 60, 83, 95, 103, 112, 142, 172, 181}

func (i PacketType) String() string {
	i -= 1
	if i >= PacketType(len(_PacketType_index)-1) {
		return "PacketType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PacketType_name[_PacketType_index[i]:_PacketType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AES-1]
}

const _CipherCryptoAlg_name = "AES"

var _CipherCryptoAlg_index = [...]uint8{0, 3}

func (i CipherCryptoAlg) String() string {
	i -= 1
	if i >= CipherCryptoAlg(len(_CipherCryptoAlg_index)-1) {
		return "CipherCryptoAlg(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CipherCryptoAlg_name[_CipherCryptoAlg_index[i]:_CipherCryptoAlg_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CBC-1]
	_ = x[GCM-2]
}

const _CipherBlockMethod_name = "CBCGCM"

var _CipherBlockMethod_index = [...]uint8{0, 3, 6}

func (i CipherBlockMethod) String() string {
	i -= 1
	if i >= CipherBlockMethod(len(_CipherBlockMethod_index)-1) {
		return "CipherBlockMethod(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CipherBlockMethod_name[_CipherBlockMethod_index[i]:_CipherBlockMethod_index[i+1]]
}
